In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as ns

arr = ns.random.rand(3,4)
print(arr)

arr2 = ns.random.randint(1,10,size=(3,4))
print(arr2)

diagonal_matrix = ns.diag([1,2,3,4])
print(diagonal_matrix)

identity_matrix = ns.eye(3)
print(identity_matrix)

[[0.73127921 0.05349647 0.5815241  0.22272092]
 [0.64912946 0.84511541 0.66477902 0.62979942]
 [0.79660761 0.38077782 0.09833012 0.3397117 ]]
[[1 5 4 9]
 [5 9 6 1]
 [5 3 2 7]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
###Transpose of a matrix

import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Transpose the matrix
transpose_matrix = matrix.T

print("Original matrix:")
print(matrix)

print("\nTransposed matrix:")
print(transpose_matrix)

Original matrix:
[[1 2 3]
 [4 5 6]]

Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]


In [10]:
### array Splitting
import numpy as np
array = np.random.randint(1, 20, size=(4, 4))
print("Original Array:")
print(array)
split_arrays = np.array_split(array, 3)
print("\nSplit Arrays:") 
print(split_arrays)
# split is used when the array can be evenly divided
even_split_arrays = np.split(array, 2)
print("\nEven Split Arrays:")
print(even_split_arrays)

Original Array:
[[ 5  2 15  5]
 [10 13  5 18]
 [ 4 16  5  3]
 [17 18  4  8]]

Split Arrays:
[array([[ 5,  2, 15,  5],
       [10, 13,  5, 18]], dtype=int32), array([[ 4, 16,  5,  3]], dtype=int32), array([[17, 18,  4,  8]], dtype=int32)]

Even Split Arrays:
[array([[ 5,  2, 15,  5],
       [10, 13,  5, 18]], dtype=int32), array([[ 4, 16,  5,  3],
       [17, 18,  4,  8]], dtype=int32)]
